### ISSUE TITLE
Declaritive template

### ISSUE THREAD

**Issue by dz0ny** [dz0ny/cdeb#1]
Implement dumb and declarative mode. Declarative creates control files from yaml structure:

```
version: 1.0-my-build
description: this package does something
deps: bash, nano, htop, python-dev
steps:
 - pre_install:
      code: |
        service app stop
 - post_install:
      code: |
        service app start
```
